# Generated by Django 6.0.6 on 2026-07-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='匿名用户', max_length=100, verbose_name='姓名')),
                ('contact', models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式')),
                ('category', models.CharField(choices=[('service', '服务质量'), ('facility', '设施设备'), ('food', '餐饮美食'), ('shopping', '商铺购物'), ('environment', '环境卫生'), ('other', '其他建议')], default='other', max_length=20, verbose_name='反馈类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('subject', models.CharField(max_length=200, verbose_name='反馈标题')),
                ('content', models.TextField(verbose_name='详细内容')),
                ('rating', models.IntegerField(default=3, verbose_name='评分(1-5)')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
